name: html2md_sample
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Jonathan White <jwhite@thinkdigital.software>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  html2md: ^0.3.2

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0

